# Docker support for local development

version: '3'
services:
  server:
    build:
      context: .
      dockerfile: ./etc/integration/Dockerfile
    environment:
      - PORT=6000
      - REDIS_URL=redis://redis:6379
    ports:
      - "6000:6000"
    depends_on:
      - redis
  redis:
    image: redis:5.0.3-alpine
    ports:
      # Expose outside the docker-compose network to facilitate local testing
      - "6379:6379"
